name: depsi
channels:
 - conda-forge
dependencies:
 - python=3.12
 - matplotlib
 - pydantic
 - pykrige
 - scipy
 - ruptures
 - networkx
 - drama
 - asf_search
 - sparse
 - scikit-learn
 - pip:
  - sarxarray>=1.2.2
  - stmtools