name: depsi
channels:
 - conda-forge
dependencies:
 - matplotlib
 - pydantic
 - pykrige
 - scipy
 - ruptures
 - networkx
 - asf_search
 - sparse
 - scikit-learn
 - pip:
     - sarxarray
     - stmtools
     - drama