name: depsi
channels:
 - conda-forge
dependencies:
 - python=3.12
 - matplotlib
 - pydantic
 - pykrige
 - sarxarray>=1.2.2
 - scipy
 - stmtools
 - ruptures
 - networkx
 - drama
 - asf_search
 - sparse
 - scikit-learn"